-- 코드를 입력하세요
SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM ANIMAL_OUTS o
WHERE (o.SEX_UPON_OUTCOME LIKE 'Spayed%' 
OR o.SEX_UPON_OUTCOME LIKE 'Neutered%')
AND o.ANIMAL_ID IN (
    SELECT ANIMAL_ID 
    FROM ANIMAL_INS i 
    WHERE i.SEX_UPON_INTAKE LIKE 'Intact%'
)
 