-- 코드를 입력하세요
-- FIRST_HALF의 SHIPMENT_ID 는 FK
-- PK는 FLAVOR
SELECT FLAVOR
FROM (
    SELECT F.FLAVOR
    FROM FIRST_HALF F
    JOIN JULY J 
    ON F.FLAVOR = J.FLAVOR
    GROUP BY F.FLAVOR
    ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
)
WHERE ROWNUM <=3;