-- 총 거래 금액 ASC

-- 코드를 입력하세요
SELECT UB.WRITER_ID AS USER_ID, U.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB
JOIN USED_GOODS_USER U ON UB.WRITER_ID = U.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UB.WRITER_ID, U.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES