-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CR ON C.CAR_ID = CR.CAR_ID
WHERE CR.START_DATE >= '2022-10-01' AND CAR_TYPE = '세단'
ORDER BY C.CAR_ID DESC;